### ISSUE TITLE
[Bug]: CLI and headless not working with python on main

### ISSUE THREAD

**Issue by mamoodi** [All-Hands-AI/OpenHands#9412]
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

Trying to run CLI and Headless via the commands from the documentation using main:
* CLI : `poetry run python -m openhands.cli.main`
* Headless: `poetry run python -m openhands.core.main -t "write a bash script that prints hi"`

They both end up with the same error. See below for logs.

### OpenHands Installation

CLI

### OpenHands Version

main

### Model Name

claude-4-sonnet

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

```
/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/openhands-ai-nUvD3lWI-py3.12/lib/python3.12/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
ERROR:root:  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/core/main.py", line 7, in <module>
    import openhands.agenthub  # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/agenthub/__init__.py", line 6, in <module>
    from openhands.agenthub import (  # noqa: E402
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/agenthub/browsing_agent/__init__.py", line 1, in <module>
    from openhands.agenthub.browsing_agent.browsing_agent import BrowsingAgent
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/agenthub/browsing_agent/browsing_agent.py", line 6, in <module>
    from openhands.agenthub.browsing_agent.response_parser import BrowsingResponseParser
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/agenthub/browsing_agent/response_parser.py", line 4, in <module>
    from openhands.controller.action_parser import ActionParser, ResponseParser
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/controller/__init__.py", line 1, in <module>
    from openhands.controller.agent_controller import AgentController
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/controller/agent_controller.py", line 25, in <module>
    from openhands.controller.agent import Agent
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/controller/agent.py", line 21, in <module>
    from openhands.runtime.plugins import PluginRequirement
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/openhands/runtime/__init__.py", line 53, in <module>
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mahmoudwork/Desktop/Main/OpenHands/third_party/runtime/impl/runloop/runloop_runtime.py", line 6, in <module>
    from runloop_api_client import Runloop
  File "/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/openhands-ai-nUvD3lWI-py3.12/lib/python3.12/site-packages/runloop_api_client/__init__.py", line 8, in <module>
    from ._client import Client, Stream, Runloop, Timeout, Transport, AsyncClient, AsyncStream, AsyncRunloop, RequestOptions
  File "/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/openhands-ai-nUvD3lWI-py3.12/lib/python3.12/site-packages/runloop_api_client/_client.py", line 24, in <module>
    from .resources import secrets, blueprints, repositories
  File "/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/openhands-ai-nUvD3lWI-py3.12/lib/python3.12/site-packages/runloop_api_client/resources/__init__.py", line 3, in <module>
    from .secrets import (
  File "/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/openhands-ai-nUvD3lWI-py3.12/lib/python3.12/site-packages/runloop_api_client/resources/secrets.py", line 18, in <module>
    from .._base_client import make_request_options
  File "/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/openhands-ai-nUvD3lWI-py3.12/lib/python3.12/site-packages/runloop_api_client/_base_client.py", line 1301, in <module>
    class _DefaultAioHttpClient(httpx_aiohttp.HttpxAiohttpClient):  # type: ignore
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ERROR:root:<class 'AttributeError'>: module 'httpx_aiohttp' has no attribute 'HttpxAiohttpClient'
```

**Comment by mamoodi** [comment]
The same commands work with OpenHands 0.46.0 so seems like a regression on main.

**Comment by mamoodi** [comment]
Looks resolved with the PR that merged. Thanks!
